/* This file was generated by syncqt. */
#ifndef QT_QTQMQTT_VERSION_H
#define QT_QTQMQTT_VERSION_H

#define QTQMQTT_VERSION_STR "1.0.0"

#define QTQMQTT_VERSION 0x010000

#endif // QT_QTQMQTT_VERSION_H
